PROJECTADM/PROJECTADM/Models/productos_Cotizaciones.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECTADM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_Cotizaciones
    {
        public int Id_producto_cotizacion { get; set; }
        public Nullable<int> Id_inventario { get; set; }
        public Nullable<int> Id_cotizacion { get; set; }
        public string Cantidad { get; set; }
    
        public virtual cotizacione cotizacione { get; set; }
        public virtual inventario inventario { get; set; }
    }
}

PROJECTADM/PROJECTADM/Controllers/productos_CotizacionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PROJECTADM.Models;

namespace PROJECTADM.Controllers
{
    public class productos_CotizacionesController : Controller
    {
        private ADMEntities db = new ADMEntities();

        // GET: productos_Cotizaciones
        public ActionResult Index(int? id, string busqueda1)
        {

           
            var productosEspecificos = from data in db.productos_Cotizaciones where data.Id_cotizacion == id select data;
            var productos_Cotizaciones = db.productos_Cotizaciones.Include(p => p.cotizacione).Include(p => p.inventario);
            var Lista = from data in db.productos_Cotizaciones select data;
            if (string.IsNullOrEmpty(busqueda1))
            {
                return View(productosEspecificos.ToList());
            }
            else
            {
                Lista = Lista.Where(a => a.Id_cotizacion.Equals(Convert.ToInt32(busqueda1)));
                return View(productosEspecificos.ToList());

            }

            
        }

        // GET: productos_Cotizaciones/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            productos_Cotizaciones productos_Cotizaciones = db.productos_Cotizaciones.Find(id);
            if (productos_Cotizaciones == null)
            {
                return HttpNotFound();
            }
            return View(productos_Cotizaciones);
        }

        // GET: productos_Cotizaciones/Create
        public ActionResult Create()
        {
            ViewBag.Id_cotizacion = new SelectList(db.cotizaciones, "Id_cotizacion", "Nombre");
            ViewBag.Id_inventario = new SelectList(db.inventarios, "Id_inventario", "Marca");
            return View();
        }

        // POST: productos_Cotizaciones/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_producto_cotizacion,Id_inventario,Id_cotizacion,Cantidad")] productos_Cotizaciones productos_Cotizaciones,int Id_cotizacion, int Id_inventario)
        {
            
            if (ModelState.IsValid)
            {
                var query = (from a in db.cotizaciones
                             where a.Id_cotizacion == Id_cotizacion
                             select a).FirstOrDefault();
                var precio =  (from a in db.inventarios
                             where a.Id_inventario == Id_inventario
                               select a).FirstOrDefault();

                query.Monto =query.Monto + precio.precio * Convert.ToInt32(productos_Cotizaciones.Cantidad) ;
                db.SaveChanges();
                query.Impuestos = query.Monto * 18/100;
                db.SaveChanges();
                query.Monto_total = query.Monto + query.Impuestos;
              
                db.productos_Cotizaciones.Add(productos_Cotizaciones);

                db.SaveChanges();
                return RedirectToAction("Index", new { id = productos_Cotizaciones.Id_cotizacion });
                
            }

            ViewBag.Id_cotizacion = new SelectList(db.cotizaciones, "Id_cotizacion", "Nombre", productos_Cotizaciones.Id_cotizacion);
            ViewBag.Id_inventario = new SelectList(db.inventarios, "Id_inventario", "Marca", productos_Cotizaciones.Id_inventario);
            return View(productos_Cotizaciones);
        }

        // GET: productos_Cotizaciones/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            productos_Cotizaciones productos_Cotizaciones = db.productos_Cotizaciones.Find(id);
            if (productos_Cotizaciones == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id_cotizacion = new SelectList(db.cotizaciones, "Id_cotizacion", "Nombre", productos_Cotizaciones.Id_cotizacion);
            ViewBag.Id_inventario = new SelectList(db.inventarios, "Id_inventario", "Marca", productos_Cotizaciones.Id_inventario);
            return View(productos_Cotizaciones);
        }

        // POST: productos_Cotizaciones/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_producto_cotizacion,Id_inventario,Id_cotizacion,Cantidad")] productos_Cotizaciones productos_Cotizaciones)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productos_Cotizaciones).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = productos_Cotizaciones.Id_cotizacion });
            }
            ViewBag.Id_cotizacion = new SelectList(db.cotizaciones, "Id_cotizacion", "Nombre", productos_Cotizaciones.Id_cotizacion);
            ViewBag.Id_inventario = new SelectList(db.inventarios, "Id_inventario", "Marca", productos_Cotizaciones.Id_inventario);
            return View(productos_Cotizaciones);
        }

        // GET: productos_Cotizaciones/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            productos_Cotizaciones productos_Cotizaciones = db.productos_Cotizaciones.Find(id);
            if (productos_Cotizaciones == null)
            {
                return HttpNotFound();
            }
            return View(productos_Cotizaciones);
        }

        // POST: productos_Cotizaciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            productos_Cotizaciones productos_Cotizaciones = db.productos_Cotizaciones.Find(id);
            db.productos_Cotizaciones.Remove(productos_Cotizaciones);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = productos_Cotizaciones.Id_cotizacion });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PROJECTADM/PROJECTADM/Views/productos_Cotizaciones/Create.cshtml
@model PROJECTADM.Models.productos_Cotizaciones

@{
    ViewBag.Title = "Create";
}

<h2>Crear</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>productos_Cotizaciones</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Id_inventario, "Id_inventario", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_inventario", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_inventario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_cotizacion, "Id_cotizacion", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_cotizacion", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_cotizacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-danger" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Regresar", "Index",null,new { @class = "btn btn-danger" })
      
    </div>

PROJECTADM/PROJECTADM/Views/productos_Cotizaciones/Delete.cshtml
@model PROJECTADM.Models.productos_Cotizaciones

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>productos Cotizaciones</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cotizacione.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cotizacione.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.inventario.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.inventario.Marca)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Regresar", "Index",null,new { @class = "btn btn-danger" })
        </div>
    }
</div>

PROJECTADM/PROJECTADM/Views/productos_Cotizaciones/Details.cshtml
@model PROJECTADM.Models.productos_Cotizaciones

@{
    ViewBag.Title = "Details";
}

<h2>Detailles</h2>

<div>
    <h4>Productos Cotizaciones</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cotizacione.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cotizacione.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.inventario.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.inventario.Marca)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id_producto_cotizacion }) |
    @Html.ActionLink("Regresar", "Index")
</p>

PROJECTADM/PROJECTADM/Views/productos_Cotizaciones/Edit.cshtml
@model PROJECTADM.Models.productos_Cotizaciones

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>productos_Cotizaciones</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id_producto_cotizacion)

        <div class="form-group">
            @Html.LabelFor(model => model.Id_inventario, "Id_inventario", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_inventario", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_inventario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_cotizacion, "Id_cotizacion", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_cotizacion", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_cotizacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Editar" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index",null,new { @class = "btn btn-danger" })
</div>

PROJECTADM/PROJECTADM/Views/productos_Cotizaciones/Index.cshtml
@model IEnumerable<PROJECTADM.Models.productos_Cotizaciones>

@{
    ViewBag.Title = "Index";
}

<h2>Seleccione los productos de la cotizacion</h2>
<br />
<br />
<p>
    @Html.ActionLink("Agregar otro producto", "Create", null, new { @class = "btn btn-danger" })
</p>

@using (Html.BeginForm("Index", "productos_Cotizaciones", FormMethod.Post))
{

    <div class="form-group pull-right">
        @Html.Label("Buscar por nombre:", htmlAttributes: new { @class = "control-label col-md-4" })

        @Html.Editor("busqueda1")
        <input type="submit" value="Buscar" class="btn btn-danger" />

        @*@Html.ValidationMessageFor(model => model.Año, "", new { @class = "text-danger" })*@
       


    </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Cantidad)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.inventario.Marca)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.inventario.Marca)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id_producto_cotizacion }, new { @class = "btn btn-danger" }) |
                @Html.ActionLink("Detalles", "Details", new { id = item.Id_producto_cotizacion }, new { @class = "btn btn-danger" }) |
                @Html.ActionLink("Borrar", "Delete", new { id = item.Id_producto_cotizacion }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>
@Html.ActionLink("Imprimir", "ExportFactura", "cotizaciones", null, new { @class = "btn btn-danger" })
@Html.ActionLink("Cancelar", "IndexCotizacion", "Home", null, new { @class = "btn btn-danger" })