PROJECTADM/PROJECTADM/Models/factura.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECTADM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factura()
        {
            this.productos_factura = new HashSet<productos_factura>();
        }
    
        public int Id_factura { get; set; }
        public Nullable<int> Id_cliente { get; set; }
        public Nullable<int> monto { get; set; }
        public Nullable<int> impuesto { get; set; }
        public Nullable<int> Monto_total { get; set; }
        public string Estado { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productos_factura> productos_factura { get; set; }
    }
}

PROJECTADM/PROJECTADM/Controllers/facturasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CrystalDecisions.CrystalReports.Engine;
using PROJECTADM.Models;

namespace PROJECTADM.Controllers
{
    public class facturasController : Controller
    {
        private ADMEntities db = new ADMEntities();

        // GET: facturas
        public ActionResult Index()
        {
            var facturas = db.facturas.Include(f => f.cliente);
            return View(facturas.ToList());
        }
        public ActionResult Index2()
        {
            var facturas = db.facturas.Include(f => f.cliente).Where(f=>f.Estado=="no pagado");

            return View(facturas.ToList());
        }

        // GET: facturas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            factura factura = db.facturas.Find(id);
            if (factura == null)
            {
                return HttpNotFound();
            }
            return View(factura);
        }

        // GET: facturas/Create
        public ActionResult Create()
        {
            ViewBag.Id_cliente = new SelectList(db.clientes, "Id_cliente", "Nombre");
            return View();
        }

        // POST: facturas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_factura,Id_cliente,monto,impuesto,Monto_total,Estado")] factura factura)
        {
            if (ModelState.IsValid)
            {
                db.facturas.Add(factura);
                db.SaveChanges();
                return RedirectToAction("Index","productos_factura", new { id = factura.Id_factura });
            }

            ViewBag.Id_cliente = new SelectList(db.clientes, "Id_cliente", "Nombre", factura.Id_cliente);
            return View(factura);
        }

        // GET: facturas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            factura factura = db.facturas.Find(id);
            if (factura == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id_cliente = new SelectList(db.clientes, "Id_cliente", "Nombre", factura.Id_cliente);
            return View(factura);
        }

        // POST: facturas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_factura,Id_cliente,monto,impuesto,Monto_total,Estado")] factura factura)
        {
            if (ModelState.IsValid)
            {
                db.Entry(factura).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index2");
            }
            ViewBag.Id_cliente = new SelectList(db.clientes, "Id_cliente", "Nombre", factura.Id_cliente);
            return View(factura);
        }

        // GET: facturas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            factura factura = db.facturas.Find(id);
            if (factura == null)
            {
                return HttpNotFound();
            }
            return View(factura);
        }

        // POST: facturas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            factura factura = db.facturas.Find(id);
            db.facturas.Remove(factura);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult ExportFactura()
        {
            List<cotizacione> allOrdenes = new List<cotizacione>();
            allOrdenes = db.cotizaciones.ToList();


            ReportDocument rd = new ReportDocument();
            rd.Load(Path.Combine(Server.MapPath("~/Reporte"), "FacturaF.rpt"));

            var lista = from data in db.proveedores

                        select data;

            //rd.SetDataSource(db2.FacturaCotizacion3(14).ToList());



            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();


            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);
            return File(stream, "application/pdf", "FacturaF.pdf");
        }

        public ActionResult ExportFacturacion()
        {
            List<cotizacione> allOrdenes = new List<cotizacione>();
            allOrdenes = db.cotizaciones.ToList();


            ReportDocument rd = new ReportDocument();
            rd.Load(Path.Combine(Server.MapPath("~/Reporte"), "Facturaciones.rpt"));

            var lista = from data in db.proveedores

                        select data;

            //rd.SetDataSource(db2.FacturaCotizacion3(14).ToList());



            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();


            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);
            return File(stream, "application/pdf", "Facturaciones.pdf");
        }

    }
}

PROJECTADM/PROJECTADM/Views/facturas/Create.cshtml
@model PROJECTADM.Models.factura

@{
    ViewBag.Title = "Create";
}

<h2>Crear</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Factura</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Id_cliente, "Id_cliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_cliente", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_cliente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.monto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.monto, new { htmlAttributes = new { @class = "form-control", @Value = 0, @readonly = "readonly"  } })
                @Html.ValidationMessageFor(model => model.monto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.impuesto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.impuesto, new { htmlAttributes = new { @class = "form-control" , @Value = 0, @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.impuesto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Monto_total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Monto_total, new { htmlAttributes = new { @class = "form-control" , @Value = 0, @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Monto_total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
            
                @Html.DropDownListFor(model => model.Estado, new MultiSelectList(new[] { "Pagado", "No pagado" }), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index",null,new { @class = "btn btn-danger" })
</div>

PROJECTADM/PROJECTADM/Views/facturas/Delete.cshtml
@model PROJECTADM.Models.factura

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>factura</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.monto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.monto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.impuesto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.impuesto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Monto_total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monto_total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cliente.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cliente.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-danger" /> |
            @Html.ActionLink("Regresar", "Index",null,new { @class = "btn btn-danger" })
        </div>
    }
</div>

PROJECTADM/PROJECTADM/Views/facturas/Details.cshtml
@model PROJECTADM.Models.factura

@{
    ViewBag.Title = "Details";
}

<h2>Detalles</h2>

<div>
    <h4>Factura</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.monto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.monto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.impuesto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.impuesto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Monto_total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monto_total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cliente.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cliente.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id_factura },new { @class = "btn btn-danger" }) |
    @Html.ActionLink("Regresar", "Index",null,new { @class = "btn btn-danger" })
</p>

PROJECTADM/PROJECTADM/Views/facturas/Edit.cshtml
@model PROJECTADM.Models.factura

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Factura</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id_factura)

        <div class="form-group">
            @Html.LabelFor(model => model.Id_cliente, "Id_cliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_cliente", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_cliente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.monto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.monto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.monto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.impuesto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.impuesto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.impuesto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Monto_total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Monto_total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Monto_total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Estado, new MultiSelectList(new[] { "Pagado", "No pagado" }), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index2",null,new { @class = "btn btn-danger" })
</div>

PROJECTADM/PROJECTADM/Views/facturas/Index.cshtml
@model IEnumerable<PROJECTADM.Models.factura>

@{
    ViewBag.Title = "Index";
}

<h2>Factura</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-danger" })
</p>
@using (Html.BeginForm("Index", "productos_Cotizaciones", FormMethod.Post))
{

    <div class="form-group pull-right">
        @Html.Label("Buscar por nombre:", htmlAttributes: new { @class = "control-label col-md-4" })

        @Html.Editor("busqueda1")
        <input type="submit" value="Buscar" class="btn btn-danger" />

        @*@Html.ValidationMessageFor(model => model.Año, "", new { @class = "text-danger" })*@


    </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.monto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.impuesto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Monto_total)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cliente.Nombre)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.monto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.impuesto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Monto_total)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cliente.Nombre)
            </td>
            <td>

                @Html.ActionLink("Details", "Details", new { id = item.Id_factura }, new { @class = "btn btn-danger" }) |

            </td>
        </tr>
    }

</table>

PROJECTADM/PROJECTADM/Views/facturas/Index2.cshtml
@model IEnumerable<PROJECTADM.Models.factura>

@{
    ViewBag.Title = "Index2";
}

<h2>Cuentas por cobrar</h2>

@using (Html.BeginForm("Index", "productos_Cotizaciones", FormMethod.Post))
{

    <div class="form-group pull-right">
        @Html.Label("Buscar por nombre:", htmlAttributes: new { @class = "control-label col-md-4" })

        @Html.Editor("busqueda1")
        <input type="submit" value="Buscar" class="btn btn-danger" />

        @*@Html.ValidationMessageFor(model => model.Año, "", new { @class = "text-danger" })*@


    </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.monto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.impuesto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Monto_total)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cliente.Nombre)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.monto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.impuesto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Monto_total)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cliente.Nombre)
            </td>
            <td>
                @Html.ActionLink("Detalles", "Details", new { id = item.Id_factura }, new { @class = "btn btn-danger" }) |
                @Html.ActionLink(" Borrar", "Delete", new { id = item.Id_factura }, new { @class = "btn btn-danger" })
                @Html.ActionLink("Detalles Cliente", "Details", "clientes", new { id = item.Id_cliente }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>
@Html.ActionLink("Imprimir", "ExportFacturacion", "facturas", null, new { @class = "btn btn-danger" })